### ISSUE TITLE
Hardware modulator envelope behavior clarifications

### ISSUE THREAD

**Issue by Kouzeru** [digital-sound-antiques/emu2413#8]
Grettings,
would you consider to test this on the real hardware, on how the modulator should behave?

First is the modulator envelope precision, and the envelope behavior when key is off after key on.
This file containing .nsf and the .wav of what this API sounded like.
[mod release test.zip](https://github.com/digital-sound-antiques/emu2413/files/6232828/mod.release.test.zip)

**Comment by Kouzeru** [comment]
This is the output from emu2413 ver 1.2.7
[mod release test - 1.2.7.zip](https://github.com/digital-sound-antiques/emu2413/files/6233032/mod.release.test.-.1.2.7.zip)

**Comment by okaxaki** [comment]
I cannot understand the purpose of the test attached. 

- Is this test a bug report for emu2413, or just test for your interest?
- What kind of things would you like to confirm on the modulator envelope? 
- Did the first `mod release test.zip` record from a VRC7 real-chip? or some NES emulator??

Anyway .nsf file is not suitable for me to verify the behavior (because i have no real h/w for playing .nsf). if possible, please attach a .vgm file.

**Comment by Kouzeru** [comment]
Sorry for some late reply

> Did the first mod release test.zip record from a VRC7 real-chip? or some NES emulator?

The first attachment recorded from nsfplay which uses the latest emu2413 (v1.5.6)


I'm also demonstrating how the both versions of emu2413 behaves on slow envelope attack of modulator:

https://user-images.githubusercontent.com/46141631/123014983-f5421c00-d3f9-11eb-9b51-6da189e47b08.mp4

the top is from which uses emu2413 v1.2.7; the bottom is from which uses v1.5.6

> Is this test a bug report for emu2413, or just test for your interest?

I don't know whether this is a bug report just because it sounded a bit off, where the modulator steps are so coarse, and the behavior of the key release are so different on both versions. Or just from my interest just because I dislike how it sounds.

> What kind of things would you like to confirm on the modulator envelope?

I want to see whether the test sounds matches original hardware so it can be confirmed, which I don't have one.

Here the things I'm complaining about, I'm wondering which is correct to the hardware?
![vrc7mod](https://user-images.githubusercontent.com/46141631/123017256-cb3f2880-d3fe-11eb-8aa1-b903949afb33.png)

and oops, I couldn't find a proper tool to convert any nsf into vgm 😓
especially ones that actually work on real hardware

**Comment by okaxaki** [comment]
Hi, thank you for detailed information!

## Coarse Envelope
Different from other YM family chips, YM2413's envelope is very coarse.
I think the envelope is correctly coarse on both v1.2.7 and 1.5.6. Please make sure the emulation core versions you use. Older (<1.0.0) emu2413's envelope is fine grained but wrong implementation.

![Attack](https://user-images.githubusercontent.com/8530297/123096073-ae8c0a80-d469-11eb-9d26-572e7e5792a9.png)

## Envelope behaviour after key-off

STUCK is the correct behavior. YM2413 has no release phase after key-off on the modulator envelope (Sorry that 1.2.7's envelope generator is buggy - it's the reason why I created the pull request to nsfplay [here](https://github.com/bbbradsmith/nsfplay/pull/39)).

I recorded the following 4 seconds of wave from my real YM2413 chip. We can see modulation gets stuck after key-off at 2 second.

![01210000f1f0f100](https://user-images.githubusercontent.com/8530297/123091841-c8771e80-d464-11eb-87a7-acc39fb1f636.png)
[01210000f1f0f100.wav.zip](https://github.com/digital-sound-antiques/emu2413/files/6701821/01210000f1f0f100.wav.zip)

where the user-defined voice parameters are 

```
Bin: $01 $21 $00 $00 $f1 $f0 $f1 $00
Mod: EG=0 ML=1 AR=15 DR=1 SL=15 RR=1 TL=0 FB=0
Car: EG=1 ML=1 AR=15 DR=0 SL=0 RR=0
``` 

I also recorded EG=1 version as the following:

![21210000f1f0f100](https://user-images.githubusercontent.com/8530297/123092020-fd837100-d464-11eb-8bb2-9d2357f55364.png)
[21210000f1f0f100.wav.zip](https://github.com/digital-sound-antiques/emu2413/files/6701824/21210000f1f0f100.wav.zip)

where the voice parameters are:

```
Bin: $21 $21 $00 $00 $f1 $f0 $f1 $00
Mod: EG=1 ML=1 AR=15 DR=1 SL=15 RR=1 TL=0 FB=0
Car: EG=1 ML=1 AR=15 DR=0 SL=0 RR=0
```

**Comment by Kouzeru** [comment]
Ah, I see...
Thank you for delightful answers!  It sort things out 😄
